### ISSUE TITLE
More (new?) icon paths not being caught

### ISSUE THREAD

**Issue by hlascelles** [davidcelis/quiet_safari#4]
We are seeing the following being missed in production:

`/assets/ico/apple-touch-icon-114-precomposed.png`

The regex as it stands would only catch it if it had height *and width*:

`/assets/ico/apple-touch-icon-114x114-precomposed.png`

Would you take a PR that updates the regex from:

`/apple-touch-icon(?:-\d+x\d+)?(?:-precomposed)?\.png/`

to

`/apple-touch-icon(?:-\d+)?(x\d+)?(?:-precomposed)?\.png/`

**Comment by hlascelles** [comment]
Or... make it it a (preset) configuration option so we don't have to redefine constants for now.

**Comment by davidcelis** [comment]
I'd be happy to accept a PR!

**Comment by hlascelles** [comment]
On review, we felt that blocking at the WAF would be a better fit!
